name: Release Drafter (All)

on:
  push:
    branches:
      - main

jobs:
  detect-packages:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes || '[]' }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate filters
        id: filter-setup
        run: |
          filters=$(go work edit -json | jq -r '.Use[] | "\(.DiskPath | ltrimstr("./")): \"\(.DiskPath | ltrimstr("./"))/**\""')
          echo "filters<<EOF" >> $GITHUB_OUTPUT
          echo "$filters" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3
        with:
          filters: ${{ steps.filter-setup.outputs.filters }}

  release-drafter:
    needs: detect-packages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: needs.detect-packages.outputs.packages != '[]' # Ensure job runs only if there are changes
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
    strategy:
      matrix:
        package: ${{ fromJSON(needs.detect-packages.outputs.packages || '[]') }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate dynamic config from template
        id: generate-config
        run: |
          folder="${{ matrix.package }}"
          sed "s|{{FOLDER}}|$folder|g" .github/release-drafter-template.yml > .github/release-drafter-$folder.yml
          echo "config<<EOF" >> $GITHUB_OUTPUT
          cat .github/release-drafter-$folder.yml >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Use dynamic release-drafter configuration
        uses: ReneWerner87/release-drafter@6dec4ceb1fb86b6514f11a2e7a39e1dedce709d0
        with:
          config: ${{ steps.generate-config.outputs.config }}
